---
title: "MILES"
author: "Franziska Lang"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3    
    toc_float: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (
  function(inputFile, encoding) { 
    rmarkdown::render(
      inputFile, 
      encoding = encoding, 
      output_file = file.path(dirname(inputFile), "miles_random_models.html")) }
      )
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = F)

date_today <- gsub("-", "", Sys.Date())
library(tidyverse)
library(ggpubr)
library(gridExtra)
library(gtools)
library("wesanderson")

setwd("/projects/SUMMIT/WP1.2/Literature_Cohorts/data_analysis/code/miles_publication/")

source("data_analysis/functions_evaluation_models.R")
theme_set(theme_bw())

path_plots <- "plots/"

export_plots <- F

export_table <- F
```


## Comparison best to random model 

Neoantigen candidates were randomized across patients and 10x10 CV was repeated with best hyperparameter setting for the respective setting. Here, performance of the original approach is compared to the random model . 


### 1.1 MEL + RCC

#### 1.1.1 SNVs

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/SNV/randomized_data/miles_10000_0.1.tsv"
path_best = "data_for_publication/MILES_results/SNV/miles_all/miles_10000_0.1.tsv"

p1 <- compare_random_best(path_random, path_best, class = "SNV")


```

#### 1.1.2 fusion genes


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/fusion_gene/randomized_data/miles_1000_0.4.tsv"
path_best = "data_for_publication/MILES_results/fusion_gene/miles_all/miles_1000_0.4.tsv"
p2 <- compare_random_best(path_random, path_best, class = "Fusion gene")


```


#### 1.1.3 combined


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}


path_random = "data_for_publication/MILES_results/combined/randomized_data/miles_5000_0.1.tsv"
path_best = "data_for_publication/MILES_results/combined/miles_all/miles_5000_0.1.tsv"

p3 <- compare_random_best(path_random, path_best, class = "Combined")


```



### 1.1.4 INDEL

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/INDEL/randomized_data/miles_500000_0.9.tsv"
path_best = "data_for_publication/MILES_results/INDEL/miles_all/miles_500000_0.9.tsv"


p4 <- compare_random_best(path_random, path_best, class = "INDEL")

```


### 1.2 MEL

#### 1.2.1 SNVs

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/SNV/randomized_data_mel/miles_10000000_0.1.tsv"
path_best = "data_for_publication/MILES_results/SNV/miles_mel/miles_10000000_0.1.tsv"

p5 <- compare_random_best(path_random, path_best, class = "MEL : SNV")


```

#### 1.2.2 combined


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/combined/randomized_data_mel/miles_500000_0.1.tsv"
path_best = "data_for_publication/MILES_results/combined/miles_mel/miles_500000_0.1.tsv"

p6 <- compare_random_best(path_random, path_best, class = "MEL : Combined")

```



### 1.2.3 INDEL

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/INDEL/randomized_data_mel/miles_500000_0.6.tsv"
path_best = "data_for_publication/MILES_results/INDEL/miles_mel/miles_500000_0.6.tsv"

p7 <- compare_random_best(path_random, path_best, class = "MEL : INDEL")

```

### 1.3 RCC

#### 1.3.1 SNVs

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/SNV/randomized_data_rcc_wo_SD/miles_500000_0.1.tsv"
path_best = "data_for_publication/MILES_results/SNV/miles_rcc_wo_SD/miles_500000_0.1.tsv"

p8 <- compare_random_best(path_random, path_best, class = "RCC : SNV")

```

#### 1.3.2 combined


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/combined/randomized_data_rcc_wo_SD/miles_50000_0.7.tsv"
path_best = "data_for_publication/MILES_results/combined/miles_rcc_wo_SD/miles_50000_0.7.tsv"

p9 <- compare_random_best(path_random, path_best, class = "RCC : combined")


```


#### 1.3.3 Fusion genes

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/fusion_gene/randomized_data_rcc_wo_SD/miles_10000000_0.2.tsv"
path_best = "data_for_publication/MILES_results/fusion_gene/miles_rcc_wo_SD/miles_10000000_0.2.tsv"

p10 <- compare_random_best(path_random, path_best, class = "RCC : Fusion gene")

```






## Summary


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}


if(export_plots){
   f <- paste0(path_plots, date_today, "_performance_random model_with_SD.pdf")
  pdf(f)
}
ggarrange(p1, p2, p3, p4, p5, p6, p7 ,  common.legend = TRUE,
          labels = c("C", "D", "E", "F", "G", "H", "I"),
          ncol = 3, nrow = 4)  
if(export_plots){
   dev.off()
}

if(export_plots){
   f <- paste0(path_plots, date_today, "_performance_random model_wo_SD.pdf")
  pdf(f)
}
ggarrange(p8, p9, p10, common.legend = TRUE,
          labels = c("E", "F", "G"),
          ncol = 3, nrow = 4)  
if(export_plots){
   dev.off()
}
```
