---
title: "MILES"
author: "Franziska Lang"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3    
    toc_float: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (
  function(inputFile, encoding) { 
    rmarkdown::render(
      inputFile, 
      encoding = encoding, 
      output_file = file.path(dirname(inputFile), "miles_random_models.html")) }
      )
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = F)

knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = F)


library(tidyverse)
library(ggpubr)
library(gridExtra)
library(gtools)
library(rstatix)

#ADJUST THIS PATH!
#setwd("./milneo_analysis/")


source("data_analysis/functions_evaluation_models.R")
source("data_analysis/Generate_Manuscript_Figures/config_figures.R")


path_plots <- "plots/"

export_plots <- F
```

This code generates Supplemental Figure 3. 

## Hyperparameter of best models 


```{r}

auc_overall_path <- read_delim("data_for_publication/MILES_results/results_summary_v1.tsv")

```


## Comparison best to random model 

Neoantigen candidates were randomized across patients and 10x10 CV was repeated with best hyperparameter setting for the respective setting. Here, performance of the original approach is compared to the random model . 



```{r}


auc_overall_path <- auc_overall_path %>% 
  mutate(
    path_result = paste0(
      "data_for_publication/MILES_results/",
      "/",
      mutation_type,
      "/",
      cohort_type,
      "/",
      "miles_",
      as.integer(sigma2),
      "_",
      sprintf(c, fmt = '%#.1f'),
      ".tsv"
    )
  ) %>% 
  mutate(
    path_random = paste0(
      "data_for_publication/MILES_results/",
      "/",
      mutation_type,
      "/random_",
      cohort_type,
      "/",
      "randomized_miles_",
      as.integer(sigma2),
      "_",
      c,
      ".tsv"
    )
  )
  

```


```{r}

auc_overall_path <- auc_overall_path %>%
  filter(file.exists(path_random))


```


### 1.1 MEL + RCC

#### 1.1.1 SNVs

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = auc_overall_path %>% 
  filter(cohort_type == "all_cohorts" & mutation_type == "SNV") %>% pull(path_random)
path_best = auc_overall_path %>% 
  filter(cohort_type == "all_cohorts" & mutation_type == "SNV") %>% pull(path_result)

p1 <- compare_random_best(path_random, path_best, class = "MEL + RCC : SNV")

```




### 1.2 MEL

#### 1.2.1 SNVs

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = auc_overall_path %>% 
  filter(cohort_type == "mel" & mutation_type == "SNV") %>% pull(path_random)
path_best = auc_overall_path %>% 
  filter(cohort_type == "mel" & mutation_type == "SNV") %>% pull(path_result)

p5 <- compare_random_best(path_random, path_best, class = "MEL : SNV")


```

#### 1.2.2 combined


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = auc_overall_path %>% 
  filter(cohort_type == "mel" & mutation_type == "combined") %>% pull(path_random)
path_best = auc_overall_path %>% 
  filter(cohort_type == "mel" & mutation_type == "combined") %>% pull(path_result)


p6 <- compare_random_best(path_random, path_best, class = "MEL : All mutation types")

```



## Summary


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

# show random models for MILES with median AUROC > 0.6
m <- ggarrange(
  p1,
  p6,
  p5,
  labels = c("A", "B", "C"),
  ncol = 2,
  nrow = 2
)  


if(export_plots){
   f <- paste0(path_plots, "Supplemental_Figure3.pdf")
  ggsave(f, m, units = "mm", width = 208, height = 150)
}


```
