---
title: "MILES"
author: "Franziska Lang"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3    
    toc_float: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (
  function(inputFile, encoding) { 
    rmarkdown::render(
      inputFile, 
      encoding = encoding, 
      output_file = file.path(dirname(inputFile), "miles_random_models.html")) }
      )
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = F)

date_today <- gsub("-", "", Sys.Date())
library(tidyverse)
library(ggpubr)
library(gridExtra)
library(gtools)
source( "import_data.R")

# ADJUST THIS PATH 
setwd("./miles_publication/")

theme_adju <- function(){
  theme_bw()+ 
  theme(axis.text=element_text(colour="black"))+ 
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
                  legend.position = "top",
        legend.justification="right",
      legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-10,-10,-10,-10),
      legend.title = element_blank(),
      legend.text = element_text(size = 6),
      title = element_text(size = 7),
      axis.text = element_text(size = 6),
          axis.title = element_text(size = 7))
}

theme_set(theme_adju())

source("data_analysis/functions_evaluation_models.R")

path_plots <- "plots/"

export_plots <- F

export_table <- F
```

This code generates Supplemental Figure 4. 


## Distribution of response categories

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

dat_indel_transformed$miao$response <- dat_indel_transformed$miao$best_RECIST

dat_indel_transformed2 <- lapply(dat_indel_transformed , function(x){
  x %>% distinct(patientIdentifier, .keep_all = TRUE) %>%
    select(patientIdentifier, response)
})

df_response <- bind_rows(dat_indel_transformed2, .id = "cohort")

nice_names <- c("Van Allen","Hugo", "Riaz", "Miao", "McDermott")
names(nice_names) <- c( "vanallen" ,"hugo"  ,"riaz_pre" ,"miao" ,"mcdermott_Atezo")

count_response <- df_response %>% 
  mutate(response = factor(response, levels = rev(c("CR", "PR", "SD", "PD")))) %>%
  mutate(cohort = nice_names[cohort])  %>%
  mutate(cohort = factor(cohort, levels = c("Van Allen", "Hugo", "Riaz", "Miao", "McDermott"))) %>%
  count(cohort, response, .drop = FALSE) %>%
  mutate(entity = ifelse(cohort %in% c("Van Allen", "Hugo", "Riaz"), "MEL", "RCC")) %>%
  group_by(cohort) %>%
  mutate(freq = n/sum(n))


ps4a <- count_response %>% 
  ggplot(aes(cohort,freq,  fill = response))+
  #scale_fill_manual(values = wes_palette("Zissou1", 4)) +
  geom_bar(stat = "identity")+
  ylab("Fraction of patients")

ps4b <- count_response %>%
  filter(response == "SD") %>%
  group_by(entity, .drop = FALSE) %>% 
  summarise(mean_freq = mean(freq)) %>%
  ggplot(aes(entity, mean_freq)) +
  geom_bar(stat = "identity")+
  ylab("Mean Fraction of patients with SD")+
  xlab("")


```

## Hyperparameter of best models 


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

auc_overall_path <- read_delim("data_for_publication/MILES_results/MILES_best_models_without_SD.tsv")

col_mut <- c("SNV" = "#88CCEE","INDEL" = "#CC6677", "Fusion gene" = "#DDCC77","combined" = "#117733")

ps4c <- auc_overall_path %>%
  ggplot(aes(sigma2, c, color = class, shape = entity))+
  scale_color_manual(values = col_mut)+
  scale_x_continuous(trans = "log10")+
  geom_point( size = 5)




```


## Comparison best to random model 

###  RCC

#### SNVs

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/SNV/randomized_data_rcc_wo_SD/miles_500000_0.1.tsv"
path_best = "data_for_publication/MILES_results/SNV/miles_rcc_wo_SD/miles_500000_0.1.tsv"

p8 <- compare_random_best(path_random, path_best, class = "RCC : SNV")

```

####  combined


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/combined/randomized_data_rcc_wo_SD/miles_50000_0.7.tsv"
path_best = "data_for_publication/MILES_results/combined/miles_rcc_wo_SD/miles_50000_0.7.tsv"

p9 <- compare_random_best(path_random, path_best, class = "RCC : combined")


```


#### Fusion genes

```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}

path_random = "data_for_publication/MILES_results/fusion_gene/randomized_data_rcc_wo_SD/miles_10000000_0.2.tsv"
path_best = "data_for_publication/MILES_results/fusion_gene/miles_rcc_wo_SD/miles_10000000_0.2.tsv"

p10 <- compare_random_best(path_random, path_best, class = "RCC : Fusion gene")

```





## Summary


```{r , echo=FALSE, message=FALSE, warning = FALSE, results=FALSE}


if(export_plots){
   f <- paste0(path_plots, date_today, "_Supplemental_Figure4.pdf")
  pdf(f)
}
ggarrange(ps4a,ps4b,ps4c, p8, p9, p10,
          labels = c("A", "B", "C", "D", "E", "F"),
          ncol = 2, nrow = 3)  
if(export_plots){

     dev.off()
}

```
